# Generated by Django 3.1.1 on 2020-10-11 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=5)),
                ('religion', models.CharField(max_length=50)),
                ('spouseName', models.CharField(max_length=100)),
                ('spouseOccupation', models.CharField(max_length=100)),
                ('noOfChil', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=100)),
                ('motherOccupation', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('fatherOccupation', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('brgy', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('ZIP', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.DateField(default=datetime.datetime(2020, 10, 12, 5, 26, 43, 957242))),
                ('dateRegistered', models.DateField(default=datetime.datetime(2020, 10, 12, 5, 26, 43, 957242))),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stocks', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='image')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.person')),
                ('dateRegistered', models.DateField(default=datetime.datetime(2020, 10, 12, 5, 26, 43, 957242))),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('main.person',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=5)),
                ('date_Ordered', models.DateField(default=datetime.datetime(2020, 10, 12, 5, 26, 43, 958241))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
